INSERT INTO ROLE VALUES (1,'ADMIN');



INSERT INTO MENU VALUES (1,'IDLI',20);
INSERT INTO MENU VALUES (2,'DOSA',40);
INSERT INTO MENU VALUES (3,'VADA',30);
INSERT INTO MENU VALUES (4,'PIZZA',120);
INSERT INTO MENU VALUES (5,'BREAD',20);
INSERT INTO MENU VALUES (6,'GARLIC BREAD',20);
INSERT INTO MENU VALUES (7,'EGG',20);
INSERT INTO MENU VALUES (8,'SANDWICH',50);
INSERT INTO MENU VALUES (9,'PARATHA',80);
INSERT INTO MENU VALUES (10,'NOODLES',110);
